//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolzTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HolzTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                                 Apache License
        ///                           Version 2.0, January 2004
        ///                        http://www.apache.org/licenses/
        ///
        ///   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///   1. Definitions.
        ///
        ///      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///      and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///      &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///      the copyright owner that  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Apache_2_0_txt {
            get {
                return ResourceManager.GetString("Apache-2.0.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Code Project Open License (CPOL) 1.02
        ///
        ///Preamble
        ///
        ///This License governs Your use of the Work. This License is intended to allow developers to use the Source Code and Executable Files provided as part of the Work in any application in any form. 
        ///
        ///The main points subject to the terms of the License are:
        ///- Source Code and Executable Files can be used in commercial applications; 
        ///- Source Code and Executable Files can be redistributed; and 
        ///- Source Code can be modified to create derivative works. 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPOL_1_02_txt {
            get {
                return ResourceManager.GetString("CPOL-1.02.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///
        ///Copyright (c) 2020 Sidney Krombholz
        ///
        ///This software includes the following libraries using the MIT License:
        ///
        ///ArduinoSketchUploader: Copyright (c) 2016 - 2018 Christophe Diericx
        ///ControlzEx: Copyright (c) 2015-2019 Jan Karger, Bastian Schmidt
        ///Gu.Wpf.Geometry: Copyright (c) 2015 Johan Larsson
        ///IntelHexFormatReader: Copyright (c) 2016 Christophe Diericx
        ///MahApps.Metro: Copyright (c) 2019 MahApps
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MIT_txt {
            get {
                return ResourceManager.GetString("MIT.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License (MS-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the
        ///same meaning here as under U.S. copyright law.
        ///
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///
        ///A &quot;contributor&quot; is any person that distributes its contribution  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_PL_txt {
            get {
                return ResourceManager.GetString("MS-PL.txt", resourceCulture);
            }
        }
    }
}
