package com.diddyholz.holztools

class  PreferenceKeys
{
    companion object
    {
        const val useAdvancedIpSettingsPreference = "PREFERENCE_LED_USEADVANCED"
        const val ledIsConnectedToPCPreference = "PREFERENCE_LED_ISCONNECTEDTOPC"
        const val ledAutoIPAddressPreference = "PREFERENCE_LED_AUTOIP"
        const val ledCustomIPAddressPreference = "PREFERENCE_LED_CUSTOMIP"
        const val ledCustomPortPreference = "PREFERENCE_LED_CUSTOMPORT"
        const val ledNamePreference = "PREFERENCE_LED_NAME"
        const val ledTypePreference = "PREFERENCE_LED_TYPE"
        const val ledAmountPreference = "PREFERENCE_LED_AMOUNT"
        const val ledDPinPreference = "PREFERENCE_LED_D_PIN"
        const val ledRPinPreference = "PREFERENCE_LED_R_PIN"
        const val ledGPinPreference = "PREFERENCE_LED_G_PIN"
        const val ledBPinPreference = "PREFERENCE_LED_B_PIN"
        const val ledHostNamePreference = "PREFERENCE_LED_HOSTLEDNAME"
        const val typeSpecificCat = "CAT_TYPE_SPECIFIC"
        const val modeStaticColorPreference = "PREFERENCE_MODE_STATIC_COLOR"
        const val modeStaticBrightnessPreference = "PREFERENCE_MODE_STATIC_BRIGHTNESS"
        const val modeCycleBrightnessPreference = "PREFERENCE_MODE_CYCLE_BRIGHTNESS"
        const val modeCycleSpeedPreference = "PREFERENCE_MODE_CYCLE_SPEED"
        const val modeRainbowBrightnessPreference = "PREFERENCE_MODE_RAINBOW_BRIGHTNESS"
        const val modeRainbowSpeedPreference = "PREFERENCE_MODE_RAINBOW_SPEED"
        const val modeLightningColorPreference = "PREFERENCE_MODE_LIGHTNING_COLOR"
        const val modeLightningBrightnessPreference = "PREFERENCE_MODE_LIGHTNING_BRIGHTNESS"
        const val modeOverlayDirectionPreference = "PREFERENCE_MODE_OVERLAY_DIRECTION"
        const val modeOverlaySpeedPreference = "PREFERENCE_MODE_OVERLAY_SPEED"
        const val modeSpinnerSpinnerColorPreference = "PREFERENCE_MODE_SPINNER_SPINNER_COLOR"
        const val modeSpinnerSpinnerBrightnessPreference = "PREFERENCE_MODE_SPINNER_SPINNER_BRIGHTNESS"
        const val modeSpinnerSpinnerSpeedPreference = "PREFERENCE_MODE_SPINNER_SPINNER_SPEED"
        const val modeSpinnerSpinnerLengthPreference = "PREFERENCE_MODE_SPINNER_SPINNER_LENGTH"
        const val modeSpinnerBackgroundColorPreference = "PREFERENCE_MODE_SPINNER_BACKGROUND_COLOR"
        const val modeSpinnerBackgroundBrightnessPreference = "PREFERENCE_MODE_SPINNER_BACKGROUND_BRIGHTNESS"
        const val settingsAccentColorPreference = "PREFERENCE_SETTINGS_ACCENT_COLOR"
        const val settingsDefaultPortPreference = "PREFERENCE_SETTINGS_DEFAULT_PORT"
        const val settingsNotifyOfUpdates = "PREFERENCE_SETTINGS_NOTIFYOFUPDATES"
        const val settingsConnectionTimeoutPreference = "PREFERENCE_SETTINGS_CONNECTION_TIMEOUT"
        const val userDataLedItemCountPreference = "PREFERENCE_USERDATA_LEDITEM_COUNT"
        const val userDataLedItemTypePreference = "PREFERENCE_USERDATA_LEDITEM_TYPE"
        const val userDataLedItemHostNamePreference = "PREFERENCE_USERDATA_LEDITEM_HOSTNAME"
        const val userDataLedItemCurrentModePreference = "PREFERENCE_USERDATA_LEDITEM_CURRENTMODE"
        const val userDataLedItemLedCountPreference = "PREFERENCE_USERDATA_LEDITEM_LEDCOUNT"
        const val userDataLedItemDPinPreference = "PREFERENCE_USERDATA_LEDITEM_DPIN"
        const val userDataLedItemRPinPreference = "PREFERENCE_USERDATA_LEDITEM_RPIN"
        const val userDataLedItemGPinPreference = "PREFERENCE_USERDATA_LEDITEM_GPIN"
        const val userDataLedItemBPinPreference = "PREFERENCE_USERDATA_LEDITEM_BPIN"
        const val userDataLedItemPortPreference = "PREFERENCE_USERDATA_LEDITEM_PORT"
        const val userDataLedItemIPPreference = "PREFERENCE_USERDATA_LEDITEM_IP"
        const val userDataLedItemCustomNamePreference = "PREFERENCE_USERDATA_LEDITEM_CUSTOMNAME"
        const val userDataLedItemHostLedNamePreference = "PREFERENCE_USERDATA_LEDITEM_HOSTLEDNAME"
        const val userDataLedItemIsOnPreference = "PREFERENCE_USERDATA_LEDITEM_ISON"
        const val userDataLedItemUseAdvancedIPPreference = "PREFERENCE_USERDATA_LEDITEM_ADVANCEDIP"
        const val userDataLedItemIsConnectedToPCPreference = "PREFERENCE_USERDATA_LEDITEM_CONNECTEDTOPC"
        const val userDataLedItemStaticBrightnessPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_STATIC_BRIGHTNESS"
        const val userDataLedItemStaticColorPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_STATIC_COLOR"
        const val userDataLedItemCycleBrightnessPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_CYCLE_BRIGHTNESS"
        const val userDataLedItemCycleSpeedPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_CYCLE_SPEED"
        const val userDataLedItemRainbowBrightnessPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_RAINBOW_BRIGHTNESS"
        const val userDataLedItemRainbowSpeedPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_RAINBOW_SPEED"
        const val userDataLedItemLightningBrightnessPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_LIGHTNING_BRIGHTNESS"
        const val userDataLedItemLightningColorPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_LIGHTNING_COLOR"
        const val userDataLedItemOverlaySpeedPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_OVERLAY_SPEED"
        const val userDataLedItemOverlayDirectionPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_OVERLAY_DIRECTION"
        const val userDataLedItemSpinnerSpinnerColorPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_SPINNER_SPINNER_COLOR"
        const val userDataLedItemSpinnerSpinnerBrightnessPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_SPINNER_SPINNER_BRIGHTNESS"
        const val userDataLedItemSpinnerSpinnerLengthPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_SPINNER_LENGTH"
        const val userDataLedItemSpinnerBackgroundColorPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_SPINNER_BACKGROUND_COLOR"
        const val userDataLedItemSpinnerBackgroundBrightnessPreference = "PREFERENCE_USERDATA_LEDITEM_MODE_SPINNER_BACKGROUND_BRIGHTNESS"

        const val prefixUserDataSharedPreferences = "preferences_leditem_"
    }
}